### ISSUE TITLE
Maximum time to add to variable

### ISSUE THREAD

**Issue by xNorbig** [Mirreski/Skript#16]
Maximum time, what u can add to variable in one line is 24 days and 20,52 hours. Please, add eg. add 1 year to {_variable}, but it doesn't works.

**Comment by Mirreski** [comment]
That should be added already.

Timespans were limited to about 24 days before, my version should work fine.

https://github.com/Mirreski/Skript/issues/2

**Comment by Mirreski** [comment]
Timespans are not limited anymore in my version so you can go beyond 24 days.

"add 1 year to {_variable}" doesn't work since you cannot use "year", "month". The "days" is the highest.
http://njol.ch/projects/skript/doc/classes/#timespan

But well with my version adding 365 days works fine.

```
add 365 days to {_variable}
message "%{_variable}%"
```

https://github.com/Mirreski/Skript/issues/2
