### ISSUE TITLE
Unknown command when writing in console [V8]

### ISSUE THREAD

**Issue by xNorbig** [Mirreski/Skript#21]
When u write command from Skript in console it says: Unknown command. Type "/help" for help.

**Comment by Mirreski** [comment]
Probably because of Njol's command system. The command still works in my tests but yes the "Unknown command" message comes up.

I will see if I can find anything to prevent it from getting sent.

**Comment by Mirreski** [comment]
Note to self: Bukkit logger doesn't pick up the "Unknown command. Type "/help" for help" message in console and so Skript doesn't cancel it. 

You can however cancel it by setting the system out to a custom print stream.

**Comment by Mirreski** [comment]
Fixed but if you have a plugin/addon which also sets the System.out to a another print stream this fix may as well become disabled.

It will be added to next version but If anyone gets any problems with another plugin because of this then I might remove it. But most likely other plugins that set the out stream will just overwrite the one I set in Skript and work normally without any problems(As long as the plugin loads after Skript).
