### ISSUE TITLE
Player Variable Error [V9]

### ISSUE THREAD

**Issue by policiu** [Mirreski/Skript#38]
Info:
  Java 8
  Spigot 1.8.6
  Skript config:
    use player UUIDs in variable names: true
    version: Skript-fixes-V8

Example: http://pastebin.com/tQZb6T6m

Summery: Player Variables do not recognize players on reload/relog

I have no idea why this is happening. Maybe the player is being saved as an entity(?)

**Comment by Mirreski** [comment]
Hm. are you using offline mode on server settings? (Just asking)

I will see if I can reproduce the error and find the issue.

**Comment by policiu** [comment]
Nope. Server is in online mode and none of the Spigot/Bukkit settings have been changed. Also everything in the Skript config is default, apart from 'use player UUIDs in variable names'.

**Comment by Mirreski** [comment]
What does {Players::_} contain whenever a player has left? Has {Players::_}'s size decreased?

Example:

2 players
both in {Players::_}
1 player leaves
is the size of {Players::_} still 2?
if so message the values of {Players::*} and see what they return.

Also does this happen in the normal Skript 2.2-SNAPSHOT?

Going to sleep now so you won't be getting an answer until tomorrow.

**Comment by policiu** [comment]
I did what you suggested and took some screenshots

![1](https://cloud.githubusercontent.com/assets/1704165/8790463/537e7356-2f1c-11e5-8b31-7c83f73ae440.JPG)
![2](https://cloud.githubusercontent.com/assets/1704165/8790465/538dd94a-2f1c-11e5-8a45-f45384b8700c.JPG)
![3](https://cloud.githubusercontent.com/assets/1704165/8790466/5390a30a-2f1c-11e5-947c-bcb410514aab.JPG)
![4](https://cloud.githubusercontent.com/assets/1704165/8790464/538d2a7c-2f1c-11e5-968d-b0062413d47c.JPG)

**Comment by Mirreski** [comment]
Hm okay. I edited the last comment before I went to sleep and perhaps you missed it.

"Also does this happen in the normal Skript 2.2-SNAPSHOT?"

Gonna test around with it myself today.

Edit: Seems to also happen in the normal Skript 2.2-SNAPHSHOT.

**Comment by Mirreski** [comment]
Okay this is really strange. ~~Works fine for non legit accounts(Server is in offline mode). But not for legit accounts~~ I retract this statement, It gives me different results like every time.

Doesn't seem to be happening because of "use player UUIDs in variable names" being set to true. For me it works the same with it false.

Current Test code.

```
command /variablePlayer:
    trigger:
        set {player} to player

command /testPlayer:
    trigger:
        if player is {player}:
            message "Yes"
        if {player} is player:
            message "Yes"
        send "ASDASD %{player}%" to {player}
        teleport player to {player}
        #None of these messages gets messaged after the {player} has relogged
        #Teleports the player to the location where the player left the game.
```

Edit: Also happens in Skript 2.1.2. Perhaps it has always been like this?

What happens should be that Skript stores the player object and when a player leaves and rejoin the server discards the old player object creates a new player object while Skript keeps the old player object.

I checked one thing and whenever the player have relogged the {player} variable, it returns false in the java method Player.isValid() otherwise it's true.

**Comment by Mirreski** [comment]
```
set {player} to player
#Make that player relog
#Now teleport to the variable {player}
teleport player to {player}
#It will teleport to the location the player reloged on.
#And it can even be the player that reloged who teleports.
```

Some other tests.

**Comment by policiu** [comment]
Okay. So basically there isn't any practical fix? I thought it was working before 1.8 but I'm probably not remembering correctly. Any suggestions for a work around?

**Comment by Mirreski** [comment]
I can fix it(probably) but it would be bit rough quick fix/work around in my opinion.

Where I check if the variable is of type player and if it is I check if the player inside the variable is valid if not I attempt to get the new player object through the UUID of the old player variable and sets the value of the variable to that new player object.

This means that every variable call will get a check to see if the type is a player.

I have to account to calls to single variables "{variable}" , list variables "{variable::*} and variable loops.

Edit: I think I tried a Spigot hack version 1.7.10 and it also had the problem.

**Comment by Mirreski** [comment]
I have a version you could try now.

Think of it as an early version of V9. It will say that there's a new version of Skript 2.2 Fixes on start up but ignore that since it says the newest version is V8b.

I have tested with single variables, list variables and loops. And it seems to work fine.

My test code.
http://pastebin.com/esKJRHMm

I added a Skript Config option "player variable fix" for enabling and disabling this fix. By default it is enabled.

Here you can pick the version up: 

https://www.dropbox.com/s/fmglw850ioh2avo/Skript%202.2%20Fixes%20V9%20Early%20Test.jar?dl=0

**Comment by policiu** [comment]
Thank you!

Everything is working as it should.

Edit: Didn't know what the comment and close did. My bad. Feel free to change it.

**Comment by Mirreski** [comment]
Okay that's good! (Also done that comment and close thing accidently sometimes)

Marking it as fixed. Even if we find some problem with it later I added a config option for enabling and disabling the fix if it's a major problem.
